cargo-features = ["edition"]

[package]
name = "futures-playground"
version = "0.1.0"
edition = "2018"
authors = ["tinaun <tinagma@gmail.com>"]


[dependencies]
futures-preview = "0.3.0-alpha.2"
nb = "0.1"
