cargo-features = ["edition"]

[package]
name = "futures-playground"
version = "0.1.0"
edition = "2018"
authors = ["tinaun <tinagma@gmail.com>"]


[dependencies]
futures-preview = { git = "https://github.com/rust-lang-nursery/futures-rs.git", features = ["compat"] }
hyper = "0.12"
tokio = "0.1"
