cargo-features = ["edition"]

[package]
name = "futures-playground"
version = "0.1.0"
edition = "2018"
authors = ["tinaun <tinagma@gmail.com>"]


[dependencies]
futures-core-preview = "0.3.0-alpha.1"
futures = "0.1"

[dev-dependencies]
hyper = "0.12"
tokio = "0.1"